In [11]:
#import python modules
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

<ipython-input-11-e015fcda437e>:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [12]:
df = pd.read_excel('/content/drive/MyDrive/Khai thác dữ liệu và ứng dụng - CS313.N21/Education_dataset_V2/03.sinhvien_chungchi.xlsx')

# Làm sạch dữ liệu

In [13]:
df.columns

Index(['id', 'mssv', ' ngaythi', ' url', ' loaixn', ' url_1', ' loaixn_2',
       ' listening', ' speaking', ' reading', ' writing', ' tongdiem', ' lydo',
       ' trangthai', ' ngayxl', 'Column1'],
      dtype='object')

In [14]:
# col_name formatting (remove space in col_name, lowercase)
df = df.rename(columns = {' ngaythi' : 'ngaythi',
                          ' url' : 'url',
                          ' loaixn' : 'loaixn',
                          ' url_1' : 'url_1',
                          ' loaixn_2' : 'loaixn_2',
                          ' listening' : 'listening',
                          ' speaking' : 'speaking',
                          ' reading' : 'reading',
                          ' writing' : 'writing',
                          ' tongdiem' : 'tongdiem',
                          ' lydo' : 'lydo',
                          ' trangthai' : 'trangthai',
                          ' ngayxl' : 'ngayxl',
                          'Column1' : 'unnamed:15'})

# remove col with almost nan value
df.drop(['ngayxl','unnamed:15'], axis='columns', inplace=True)

# remove url, url.1 col
df.drop(['url','url_1'], axis='columns', inplace=True)

#remove trangthai
df.drop('trangthai', axis ='columns', inplace = True)

# check col_name
df.columns

Index(['id', 'mssv', 'ngaythi', 'loaixn', 'loaixn_2', 'listening', 'speaking',
       'reading', 'writing', 'tongdiem', 'lydo'],
      dtype='object')

In [15]:
print("shape of data: sinhvien_chungchi")
print(df.shape)
print("\n------null value of each column-----")
print(df.isnull().sum().sort_values(ascending = True))

shape of data: sinhvien_chungchi
(3400, 11)

------null value of each column-----
id           10  
mssv         10  
loaixn       10  
tongdiem     10  
ngaythi      544 
lydo         784 
writing      962 
listening    1104
reading      1314
loaixn_2     3112
speaking     3112
dtype: int64


In [16]:
# check datatype of dataframe
df.dtypes

id           float64
mssv         object 
ngaythi      object 
loaixn       object 
loaixn_2     float64
listening    float64
speaking     float64
reading      object 
writing      object 
tongdiem     object 
lydo         object 
dtype: object

## Chuyển đổi kiểu dữ liệu trong các cột

> Văn bản được thụt lề





In [17]:
# clean id column
# change NaN value and strange value ('---', '..') to "0" and then convert column to int64
# remove data with id = '0'

def convert_id(id):
  try:
    id = pd.to_numeric(id)
  except:
    id = np.nan
  return id

df['id'] = df['id'].apply(lambda x: convert_id(x)).fillna(0).astype(np.int64)
df = df[df.id != 0]

In [18]:
df['mssv'] = df.mssv.apply(str)
df['mssv'].dtype

<ipython-input-18-c933621b2cd4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mssv'] = df.mssv.apply(str)


dtype('O')

In [19]:
# clean ngaythi column
# change NaN to NaT and convert column to datetime with format (Year-Month-Year)

df['ngaythi'] = pd.to_datetime(df['ngaythi'], format = '%Y-%m-%d', errors='coerce')
df['ngaythi'].unique()

<ipython-input-19-ea0c6b70d51e>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ngaythi'] = pd.to_datetime(df['ngaythi'], format = '%Y-%m-%d', errors='coerce')


array([                          'NaT', '2010-06-21T00:00:00.000000000',
       '2018-03-11T00:00:00.000000000', '2017-11-07T00:00:00.000000000',
       '2018-04-04T00:00:00.000000000', '2012-01-06T00:00:00.000000000',
       '2018-05-11T00:00:00.000000000', '2017-12-03T00:00:00.000000000',
       '2018-05-12T00:00:00.000000000', '2018-05-14T00:00:00.000000000',
       '2018-05-17T00:00:00.000000000', '2017-12-07T00:00:00.000000000',
       '2018-05-16T00:00:00.000000000', '2018-05-19T00:00:00.000000000',
       '2018-06-01T00:00:00.000000000', '2013-08-28T00:00:00.000000000',
       '2017-02-08T00:00:00.000000000', '2017-12-11T00:00:00.000000000',
       '2018-03-05T00:00:00.000000000', '2010-04-06T00:00:00.000000000',
       '2017-09-28T00:00:00.000000000', '2018-05-24T00:00:00.000000000',
       '2017-09-08T00:00:00.000000000', '2012-01-16T00:00:00.000000000',
       '2014-03-04T00:00:00.000000000', '2017-08-12T00:00:00.000000000',
       '2017-06-15T00:00:00.000000000', '2015-04-16

In [20]:
def convert_loaixn(xn):
  try:
    xn = xn.replace("'","")
    xn = xn.replace(" ","")
  except:
    loaixn = np.nan
  return xn

df['loaixn'] = df['loaixn'].apply(lambda x: convert_loaixn(x)) 
df['loaixn'].unique()

<ipython-input-20-512563585d45>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loaixn'] = df['loaixn'].apply(lambda x: convert_loaixn(x))


array(['TOIEC', 'TOEIC_LR', 'VNU-EPT', 'IELTS', 'NHAT', 'Cambrigde',
       'TOEIC_SW', 'TOEFLiBT', 'PHAP', 'DGNL'], dtype=object)

In [21]:
# CLEAN LOAIXN COLUMN
def convert_loaixn(xn):
  try:
    xn = xn.replace("'","")
    xn = xn.replace(" ","")
  except:
    loaixn = np.nan
  return xn

df['loaixn_2'] = df['loaixn_2'].apply(lambda x: convert_loaixn(x))
df['loaixn_2'].unique()

<ipython-input-21-e5204b33e3d9>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loaixn_2'] = df['loaixn_2'].apply(lambda x: convert_loaixn(x))


array([ nan, 100., 110.,  90., 115., 130., 120., 135., 150.,  95., 140.,
        80., 155.,  75., 125., 105., 175.,  85.,  70., 145., 170., 160.])

In [22]:
# CLEAN READING COLUMN
# there are 3 type of data: score(float), N3/N4(str), np.nan in column
def convert_reading(reading):
  reading = str(reading)
  reading = reading.replace("'","")
  reading = reading.replace(" ","")
  if reading == 'nan':
    return np.nan
  if 'N' in reading:
    return str(reading)
  else:
    return float(reading)

df['reading'] = df['reading'].apply(lambda x: convert_reading(x))
df['reading'].unique()

<ipython-input-22-054506c740d4>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reading'] = df['reading'].apply(lambda x: convert_reading(x))


array([nan, 515.0, 350.0, 465.0, 485.0, 405.0, 455.0, 110.0, 655.0, 6.0,
       415.0, 720.0, 685.0, 305.0, 225.0, 440.0, 155.0, 380.0, 575.0,
       450.0, 420.0, 390.0, 595.0, 670.0, 615.0, 820.0, 645.0, 475.0,
       550.0, 705.0, 435.0, 200.0, 935.0, 5.5, 610.0, 'N4', 525.0, 780.0,
       235.0, 710.0, 635.0, 675.0, 605.0, 202.0, 535.0, 141.0, 650.0,
       690.0, 600.0, 570.0, 660.0, 232.0, 775.0, 665.0, 325.0, 585.0,
       238.0, 7.0, 215.0, 890.0, 216.0, 505.0, 815.0, 565.0, 490.0, 220.0,
       885.0, 580.0, 107.0, 4.5, 260.0, 480.0, 530.0, 500.0, 6.5, 210.0,
       735.0, 960.0, 97.0, 245.0, 190.0, 250.0, 520.0, 230.0, 545.0,
       240.0, 590.0, 5.0, 725.0, 93.0, 755.0, 540.0, 625.0, 555.0, 0.0,
       715.0, 315.0, 730.0, 620.0, 895.0, 745.0, 800.0, 860.0, 495.0,
       300.0, 940.0, 700.0, 270.0, 805.0, 203.0, 470.0, 825.0, 920.0,
       460.0, 206.0, 303.0, 695.0, 760.0, 195.0, 865.0, 204.0, 179.0,
       630.0, 185.0, 855.0, 910.0, 840.0, 355.0, 234.0, 126.0, 280.0,
    

In [23]:
def convert_writing(writing):
  if writing == ' ' or writing =='':
    return np.nan
  try:
    writing = writing.replace("'","")
    writing = writing.lstrip(' ').rstrip(' ')
    return writing
  except:
    return writing 

df['writing'] = df['writing'].apply(lambda x: convert_writing(x))
df['writing'].unique()

<ipython-input-23-d184fa92ca6f>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['writing'] = df['writing'].apply(lambda x: convert_writing(x))


array([nan, 'Đạt chuẩn đầu ra', 'Miễn Anh văn 3',
       'Miễn Anh văn 3 và đạt chuẩn đầu ra', 'Miễn AV2', 'Miễn Anh văn 1',
       'Được Miễn AV1', 'SV đạt chuẩn đầu ra',
       'Chứng chỉ hợp lệ và đạt chuẩn quá trình nhưng sinh viên vẫn phải học anh văn 1.',
       'Chứng chỉ hợp lệ nhưng chứng chỉ này không đạt số điểm theo quy định để được xét tốt nghiệp và xét miễn anh văn',
       'Xác minh với TTNN', 'Chứng chỉ quá hạn',
       'Sinh viên phải úp hình chứng chỉ hoặc phiếu điểm ngoại ngữ.',
       'Em vui lòng cung cấp ID Number và Password mới xác minh được',
       'Vui lòng úp hình chứng chỉ của em.',
       'Vui lòng cập nhật hình chứng chỉ có thông tin cá nhân của em trong đó.',
       'Sinh viên vui lòng up lại chứng chỉ',
       'Chứng chỉ này không dùng để xét tốt nghiệp.',
       'Chứng chỉ đã làm lại kết quả điểm', 'Ngày thi 29/12/2018',
       'Không đủ điểm xét tốt nghiệp.',
       'Sinh viên vui lòng up chứng chỉ.',
       'Chứng nhận không dùng cho chuẩn đầu ra để 

In [24]:
# CLEAN DATA OF TONGDIEM COLUMN

def convert_tongdiem(diem):
  try:
    diem = diem.replace("'","")
    diem = diem.lstrip(' ').rstrip(' ')
    return diem
  except:
    return diem

df['tongdiem'] = df.tongdiem.apply(lambda x: convert_tongdiem(x))
df['tongdiem'].unique()

<ipython-input-24-67dcf020710b>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tongdiem'] = df.tongdiem.apply(lambda x: convert_tongdiem(x))


array(['1', '3 và Đạt chuẩn đầu ra', '2', '-1',
       'hiện tại hình chụp không rõ nên không kiểm tra được thông tin.',
       'điểm chính xác là 240.', '0',
       'sinh viên vui lòng chọn lại loại chứng chỉ', 'sv được miễn AVSC',
       'không phảiTOEIC'], dtype=object)

In [25]:
# CLEAN DATA OF LYDO COLUMN

def convert_lydo(lydo):
  try:
    lydo = lydo.replace("'",'').lstrip(' ').rstrip(' ')
    return str(lydo)
  except:
    return lydo

df['lydo'] = df['lydo'].apply(lambda x: convert_lydo(x))
df['lydo']

0       2017-09-08 13:56:09  
1       2017-09-08 13:55:15  
2       2017-09-08 13:55:27  
3       2017-09-08 13:56:00  
4       2017-09-08 13:55:51  
5       2017-09-08 13:55:42  
6       2017-10-06 14:31:31  
7       2017-10-06 14:31:13  
8       2017-10-06 14:30:49  
9       2017-10-06 14:30:07  
10      2017-10-06 14:26:24  
11      2017-10-06 14:26:00  
12      2017-10-06 14:25:18  
13      2017-10-06 14:23:46  
14      2017-10-06 14:23:08  
15      2017-10-06 14:22:22  
16      2017-10-06 14:18:34  
17      2017-10-06 14:15:42  
18      2017-10-06 14:15:03  
19      2017-10-06 14:08:39  
20      2017-11-23 10:55:25  
21      2017-12-27 08:59:54  
22      2017-12-27 09:00:47  
23      2018-01-29 15:14:34  
24      2018-01-30 09:12:59  
25      2018-01-30 09:15:08  
26      2018-01-29 15:14:58  
27      2018-01-30 09:20:11  
28      2018-02-02 10:34:31  
29      2018-02-02 09:48:58  
30      2018-02-02 10:38:45  
31      2018-02-02 10:35:41  
32      2018-02-02 10:04:52  
33      20

# Overview datatable


*   check null data
*   print data type



In [26]:
print("shape of data: sinhvien_chungchi")
print(df.shape)

print("\n------dataframe information-----\n")
print(df.info())

print("\n------5 row of datatable")
print(df.head(5))

df.to_csv('cleandata_Sinhvien_chungchi.csv')

shape of data: sinhvien_chungchi
(3390, 11)

------dataframe information-----

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3390 entries, 0 to 3399
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   id         3390 non-null   int64         
 1   mssv       3390 non-null   object        
 2   ngaythi    1413 non-null   datetime64[ns]
 3   loaixn     3390 non-null   object        
 4   loaixn_2   288 non-null    float64       
 5   listening  2296 non-null   float64       
 6   speaking   288 non-null    float64       
 7   reading    2086 non-null   object        
 8   writing    1289 non-null   object        
 9   tongdiem   3390 non-null   object        
 10  lydo       2616 non-null   object        
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 317.8+ KB
None

------5 row of datatable
   id                                      mssv ngaythi loaixn  loaixn_2  \
0  6   12C241

In [27]:
df.to_csv('03_sinhvien_chungchi.csv', index=False)